// ============================================================
// quotationService.js
// Complete service layer for the Quotations module
// Handles: CRUD, workflow transitions, order & job creation
// ============================================================

import supabase from "../../../lib/supabase";

// ─── FETCH ───────────────────────────────────────────────────

/**
 * Fetch all quotations ordered by newest first
 */
export async function fetchQuotations() {
  const { data, error } = await supabase
    .from("quotations")
    .select("*")
    .order("created_at", { ascending: false });

  if (error) {
    console.error("fetchQuotations error:", error);
    throw new Error(error.message);
  }
  return data || [];
}

/**
 * Fetch a single quotation by ID
 */
export async function fetchQuotationById(id) {
  const { data, error } = await supabase
    .from("quotations")
    .select("*")
    .eq("id", id)
    .single();

  if (error) {
    console.error("fetchQuotationById error:", error);
    throw new Error(error.message);
  }
  return data;
}

/**
 * Fetch quotations filtered by status
 */
export async function fetchQuotationsByStatus(status) {
  const { data, error } = await supabase
    .from("quotations")
    .select("*")
    .eq("status", status)
    .order("created_at", { ascending: false });

  if (error) {
    console.error("fetchQuotationsByStatus error:", error);
    throw new Error(error.message);
  }
  return data || [];
}

// ─── CREATE ──────────────────────────────────────────────────

/**
 * Create a new quotation (always starts as Draft)
 * The quotation_number is auto-generated by DB trigger
 */
export async function createQuotation(quotation) {
  const payload = {
    ...quotation,
    status: "Draft",
    quotation_number: "", // trigger will override
    converted_to_order: false,
  };

  const { data, error } = await supabase
    .from("quotations")
    .insert([payload])
    .select()
    .single();

  if (error) {
    console.error("createQuotation error:", error);
    throw new Error(error.message);
  }
  return data;
}

// ─── UPDATE ──────────────────────────────────────────────────

/**
 * Update an existing quotation (only allowed in Draft or Submitted)
 */
export async function updateQuotation(id, updates) {
  // Prevent editing of locked quotations
  const existing = await fetchQuotationById(id);
  if (!existing) throw new Error("Quotation not found.");
  if (["Approved", "Cancelled"].includes(existing.status)) {
    throw new Error(
      `Cannot edit a quotation with status "${existing.status}".`
    );
  }

  const { data, error } = await supabase
    .from("quotations")
    .update(updates)
    .eq("id", id)
    .select()
    .single();

  if (error) {
    console.error("updateQuotation error:", error);
    throw new Error(error.message);
  }
  return data;
}

// ─── DELETE ──────────────────────────────────────────────────

/**
 * Delete a quotation — only allowed when status is Draft
 */
export async function deleteQuotation(id) {
  const existing = await fetchQuotationById(id);
  if (!existing) throw new Error("Quotation not found.");
  if (existing.status !== "Draft") {
    throw new Error("Only Draft quotations can be deleted.");
  }

  const { error } = await supabase
    .from("quotations")
    .delete()
    .eq("id", id);

  if (error) {
    console.error("deleteQuotation error:", error);
    throw new Error(error.message);
  }
  return true;
}

// ─── WORKFLOW TRANSITIONS ────────────────────────────────────

/**
 * Submit a Draft quotation for approval
 */
export async function submitQuotation(id) {
  const existing = await fetchQuotationById(id);
  if (!existing) throw new Error("Quotation not found.");
  if (existing.status !== "Draft") {
    throw new Error("Only Draft quotations can be submitted.");
  }

  const { data, error } = await supabase
    .from("quotations")
    .update({
      status: "Submitted",
      submitted_at: new Date().toISOString(),
    })
    .eq("id", id)
    .select()
    .single();

  if (error) {
    console.error("submitQuotation error:", error);
    throw new Error(error.message);
  }
  return data;
}

/**
 * Approve a Submitted quotation
 * Also triggers order and production job creation
 */
export async function approveQuotation(id, approvedBy = "System") {
  const existing = await fetchQuotationById(id);
  if (!existing) throw new Error("Quotation not found.");
  if (existing.status !== "Submitted") {
    throw new Error("Only Submitted quotations can be approved.");
  }

  const { data: quotation, error } = await supabase
    .from("quotations")
    .update({
      status: "Approved",
      approved_by: approvedBy,
      approved_at: new Date().toISOString(),
    })
    .eq("id", id)
    .select()
    .single();

  if (error) {
    console.error("approveQuotation error:", error);
    throw new Error(error.message);
  }

  return quotation;
}

/**
 * Reject a Submitted quotation with a reason
 */
export async function rejectQuotation(id, reason = "") {
  const existing = await fetchQuotationById(id);
  if (!existing) throw new Error("Quotation not found.");
  if (existing.status !== "Submitted") {
    throw new Error("Only Submitted quotations can be rejected.");
  }

  const { data, error } = await supabase
    .from("quotations")
    .update({
      status: "Rejected",
      rejected_reason: reason,
      rejected_at: new Date().toISOString(),
    })
    .eq("id", id)
    .select()
    .single();

  if (error) {
    console.error("rejectQuotation error:", error);
    throw new Error(error.message);
  }
  return data;
}

/**
 * Cancel a quotation (Draft or Submitted)
 */
export async function cancelQuotation(id) {
  const existing = await fetchQuotationById(id);
  if (!existing) throw new Error("Quotation not found.");
  if (!["Draft", "Submitted"].includes(existing.status)) {
    throw new Error("Only Draft or Submitted quotations can be cancelled.");
  }

  const { data, error } = await supabase
    .from("quotations")
    .update({ status: "Cancelled" })
    .eq("id", id)
    .select()
    .single();

  if (error) {
    console.error("cancelQuotation error:", error);
    throw new Error(error.message);
  }
  return data;
}

// ─── ORDER + PRODUCTION JOB CONVERSION ───────────────────────

/**
 * Convert an Approved quotation into an Order + Production Job
 * Uses a sequential flow: create order → create production job → link back
 */
export async function convertToOrder(quotationId) {
  const quotation = await fetchQuotationById(quotationId);
  if (!quotation) throw new Error("Quotation not found.");
  if (quotation.status !== "Approved") {
    throw new Error("Only Approved quotations can be converted to orders.");
  }
  if (quotation.converted_to_order) {
    throw new Error("This quotation has already been converted to an order.");
  }

  // 1. Generate order number (format: ORD-YYYYMM-XXXX)
  const orderNumber = await generateOrderNumber();

  // 2. Create Order
  const { data: order, error: orderError } = await supabase
    .from("orders")
    .insert([
      {
        order_number: orderNumber,
        quotation_id: quotationId,
        customer_name: quotation.customer_name,
        status: "Confirmed",
        total_amount: quotation.final_price,
      },
    ])
    .select()
    .single();

  if (orderError) {
    console.error("convertToOrder (order) error:", orderError);
    throw new Error(orderError.message);
  }

  // 3. Generate job number (format: JOB-YYYYMM-XXXX)
  const jobNumber = await generateJobNumber();

  // 4. Create Production Job
  const { data: job, error: jobError } = await supabase
    .from("production_jobs")
    .insert([
      {
        job_number: jobNumber,
        order_id: order.id,
        quotation_id: quotationId,
        customer_name: quotation.customer_name,
        box_type: quotation.box_type,
        quantity: quotation.quantity,
        status: "Scheduled",
        planned_date: getPlannedDate(7), // 7 days from now
      },
    ])
    .select()
    .single();

  if (jobError) {
    console.error("convertToOrder (job) error:", jobError);
    throw new Error(jobError.message);
  }

  // 5. Link back to quotation
  const { data: updatedQuotation, error: linkError } = await supabase
    .from("quotations")
    .update({
      converted_to_order: true,
      order_id: order.id,
      production_job_id: job.id,
    })
    .eq("id", quotationId)
    .select()
    .single();

  if (linkError) {
    console.error("convertToOrder (link) error:", linkError);
    throw new Error(linkError.message);
  }

  return { quotation: updatedQuotation, order, job };
}

// ─── HELPERS ─────────────────────────────────────────────────

async function generateOrderNumber() {
  const yyyymm = new Date().toISOString().slice(0, 7).replace("-", "");
  const { count } = await supabase
    .from("orders")
    .select("id", { count: "exact", head: true });
  const seq = String((count || 0) + 1).padStart(4, "0");
  return `ORD-${yyyymm}-${seq}`;
}

async function generateJobNumber() {
  const yyyymm = new Date().toISOString().slice(0, 7).replace("-", "");
  const { count } = await supabase
    .from("production_jobs")
    .select("id", { count: "exact", head: true });
  const seq = String((count || 0) + 1).padStart(4, "0");
  return `JOB-${yyyymm}-${seq}`;
}

function getPlannedDate(daysFromNow) {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().split("T")[0];
}